//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainParaPruebas.ServicioSOAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioSOAP.ISL_Soap")]
    public interface ISL_Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISL_Soap/EchoTest", ReplyAction="http://tempuri.org/ISL_Soap/EchoTestResponse")]
        string EchoTest(string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISL_Soap/EchoTest", ReplyAction="http://tempuri.org/ISL_Soap/EchoTestResponse")]
        System.Threading.Tasks.Task<string> EchoTestAsync(string mensaje);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISL_SoapChannel : MainParaPruebas.ServicioSOAP.ISL_Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SL_SoapClient : System.ServiceModel.ClientBase<MainParaPruebas.ServicioSOAP.ISL_Soap>, MainParaPruebas.ServicioSOAP.ISL_Soap {
        
        public SL_SoapClient() {
        }
        
        public SL_SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SL_SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SL_SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SL_SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string EchoTest(string mensaje) {
            return base.Channel.EchoTest(mensaje);
        }
        
        public System.Threading.Tasks.Task<string> EchoTestAsync(string mensaje) {
            return base.Channel.EchoTestAsync(mensaje);
        }
    }
}
