//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalAutogestion.ServiceSOAP {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ViajeDisponibleDTO", Namespace="http://schemas.datacontract.org/2004/07/Share.DTOs")]
    [System.SerializableAttribute()]
    public partial class ViajeDisponibleDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] asientos_disponiblesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan horaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int parada_id_destinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int parada_id_origenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal precioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int viaje_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] asientos_disponibles {
            get {
                return this.asientos_disponiblesField;
            }
            set {
                if ((object.ReferenceEquals(this.asientos_disponiblesField, value) != true)) {
                    this.asientos_disponiblesField = value;
                    this.RaisePropertyChanged("asientos_disponibles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan hora {
            get {
                return this.horaField;
            }
            set {
                if ((this.horaField.Equals(value) != true)) {
                    this.horaField = value;
                    this.RaisePropertyChanged("hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int parada_id_destino {
            get {
                return this.parada_id_destinoField;
            }
            set {
                if ((this.parada_id_destinoField.Equals(value) != true)) {
                    this.parada_id_destinoField = value;
                    this.RaisePropertyChanged("parada_id_destino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int parada_id_origen {
            get {
                return this.parada_id_origenField;
            }
            set {
                if ((this.parada_id_origenField.Equals(value) != true)) {
                    this.parada_id_origenField = value;
                    this.RaisePropertyChanged("parada_id_origen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int viaje_id {
            get {
                return this.viaje_idField;
            }
            set {
                if ((this.viaje_idField.Equals(value) != true)) {
                    this.viaje_idField = value;
                    this.RaisePropertyChanged("viaje_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoDocumento", Namespace="http://schemas.datacontract.org/2004/07/Share.Enums")]
    public enum TipoDocumento : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CI = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OTROS = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pasaje", Namespace="http://schemas.datacontract.org/2004/07/Share.Entities")]
    [System.SerializableAttribute()]
    public partial class Pasaje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> asientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Parada parada_destinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Parada parada_origenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<TerminalAutogestion.ServiceSOAP.TipoDocumento> tipo_documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool usadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Usuario usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Viaje viajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> asiento {
            get {
                return this.asientoField;
            }
            set {
                if ((this.asientoField.Equals(value) != true)) {
                    this.asientoField = value;
                    this.RaisePropertyChanged("asiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string documento {
            get {
                return this.documentoField;
            }
            set {
                if ((object.ReferenceEquals(this.documentoField, value) != true)) {
                    this.documentoField = value;
                    this.RaisePropertyChanged("documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Parada parada_destino {
            get {
                return this.parada_destinoField;
            }
            set {
                if ((object.ReferenceEquals(this.parada_destinoField, value) != true)) {
                    this.parada_destinoField = value;
                    this.RaisePropertyChanged("parada_destino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Parada parada_origen {
            get {
                return this.parada_origenField;
            }
            set {
                if ((object.ReferenceEquals(this.parada_origenField, value) != true)) {
                    this.parada_origenField = value;
                    this.RaisePropertyChanged("parada_origen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<TerminalAutogestion.ServiceSOAP.TipoDocumento> tipo_documento {
            get {
                return this.tipo_documentoField;
            }
            set {
                if ((this.tipo_documentoField.Equals(value) != true)) {
                    this.tipo_documentoField = value;
                    this.RaisePropertyChanged("tipo_documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool usado {
            get {
                return this.usadoField;
            }
            set {
                if ((this.usadoField.Equals(value) != true)) {
                    this.usadoField = value;
                    this.RaisePropertyChanged("usado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Usuario usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Viaje viaje {
            get {
                return this.viajeField;
            }
            set {
                if ((object.ReferenceEquals(this.viajeField, value) != true)) {
                    this.viajeField = value;
                    this.RaisePropertyChanged("viaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parada", Namespace="http://schemas.datacontract.org/2004/07/Share.Entities")]
    [System.SerializableAttribute()]
    public partial class Parada : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal latitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal longitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Pasaje[] pasajes_destinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Pasaje[] pasajes_origenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Tramo[] tramosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal latitud {
            get {
                return this.latitudField;
            }
            set {
                if ((this.latitudField.Equals(value) != true)) {
                    this.latitudField = value;
                    this.RaisePropertyChanged("latitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal longitud {
            get {
                return this.longitudField;
            }
            set {
                if ((this.longitudField.Equals(value) != true)) {
                    this.longitudField = value;
                    this.RaisePropertyChanged("longitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Pasaje[] pasajes_destino {
            get {
                return this.pasajes_destinoField;
            }
            set {
                if ((object.ReferenceEquals(this.pasajes_destinoField, value) != true)) {
                    this.pasajes_destinoField = value;
                    this.RaisePropertyChanged("pasajes_destino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Pasaje[] pasajes_origen {
            get {
                return this.pasajes_origenField;
            }
            set {
                if ((object.ReferenceEquals(this.pasajes_origenField, value) != true)) {
                    this.pasajes_origenField = value;
                    this.RaisePropertyChanged("pasajes_origen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Tramo[] tramos {
            get {
                return this.tramosField;
            }
            set {
                if ((object.ReferenceEquals(this.tramosField, value) != true)) {
                    this.tramosField = value;
                    this.RaisePropertyChanged("tramos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/Share.Entities")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Pasaje[] pasajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Persona personaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Pasaje[] pasaje {
            get {
                return this.pasajeField;
            }
            set {
                if ((object.ReferenceEquals(this.pasajeField, value) != true)) {
                    this.pasajeField = value;
                    this.RaisePropertyChanged("pasaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Persona persona {
            get {
                return this.personaField;
            }
            set {
                if ((object.ReferenceEquals(this.personaField, value) != true)) {
                    this.personaField = value;
                    this.RaisePropertyChanged("persona");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Viaje", Namespace="http://schemas.datacontract.org/2004/07/Share.Entities")]
    [System.SerializableAttribute()]
    public partial class Viaje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> finalizadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Horario horarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Pasaje[] pasajesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> finalizado {
            get {
                return this.finalizadoField;
            }
            set {
                if ((this.finalizadoField.Equals(value) != true)) {
                    this.finalizadoField = value;
                    this.RaisePropertyChanged("finalizado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Horario horario {
            get {
                return this.horarioField;
            }
            set {
                if ((object.ReferenceEquals(this.horarioField, value) != true)) {
                    this.horarioField = value;
                    this.RaisePropertyChanged("horario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Pasaje[] pasajes {
            get {
                return this.pasajesField;
            }
            set {
                if ((object.ReferenceEquals(this.pasajesField, value) != true)) {
                    this.pasajesField = value;
                    this.RaisePropertyChanged("pasajes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tramo", Namespace="http://schemas.datacontract.org/2004/07/Share.Entities")]
    [System.SerializableAttribute()]
    public partial class Tramo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Linea lineaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Parada paradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Precio[] precioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> tiempoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Linea linea {
            get {
                return this.lineaField;
            }
            set {
                if ((object.ReferenceEquals(this.lineaField, value) != true)) {
                    this.lineaField = value;
                    this.RaisePropertyChanged("linea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numero {
            get {
                return this.numeroField;
            }
            set {
                if ((this.numeroField.Equals(value) != true)) {
                    this.numeroField = value;
                    this.RaisePropertyChanged("numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Parada parada {
            get {
                return this.paradaField;
            }
            set {
                if ((object.ReferenceEquals(this.paradaField, value) != true)) {
                    this.paradaField = value;
                    this.RaisePropertyChanged("parada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Precio[] precio {
            get {
                return this.precioField;
            }
            set {
                if ((object.ReferenceEquals(this.precioField, value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> tiempo {
            get {
                return this.tiempoField;
            }
            set {
                if ((this.tiempoField.Equals(value) != true)) {
                    this.tiempoField = value;
                    this.RaisePropertyChanged("tiempo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Linea", Namespace="http://schemas.datacontract.org/2004/07/Share.Entities")]
    [System.SerializableAttribute()]
    public partial class Linea : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Horario[] horariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Tramo[] tramosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Horario[] horarios {
            get {
                return this.horariosField;
            }
            set {
                if ((object.ReferenceEquals(this.horariosField, value) != true)) {
                    this.horariosField = value;
                    this.RaisePropertyChanged("horarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Tramo[] tramos {
            get {
                return this.tramosField;
            }
            set {
                if ((object.ReferenceEquals(this.tramosField, value) != true)) {
                    this.tramosField = value;
                    this.RaisePropertyChanged("tramos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Precio", Namespace="http://schemas.datacontract.org/2004/07/Share.Entities")]
    [System.SerializableAttribute()]
    public partial class Precio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_validezField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Tramo tramoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal valorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_validez {
            get {
                return this.fecha_validezField;
            }
            set {
                if ((this.fecha_validezField.Equals(value) != true)) {
                    this.fecha_validezField = value;
                    this.RaisePropertyChanged("fecha_validez");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Tramo tramo {
            get {
                return this.tramoField;
            }
            set {
                if ((object.ReferenceEquals(this.tramoField, value) != true)) {
                    this.tramoField = value;
                    this.RaisePropertyChanged("tramo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal valor {
            get {
                return this.valorField;
            }
            set {
                if ((this.valorField.Equals(value) != true)) {
                    this.valorField = value;
                    this.RaisePropertyChanged("valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Horario", Namespace="http://schemas.datacontract.org/2004/07/Share.Entities")]
    [System.SerializableAttribute()]
    public partial class Horario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Conductor conductorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan horaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Linea lineaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Vehiculo vehiculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Viaje[] viajesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Conductor conductor {
            get {
                return this.conductorField;
            }
            set {
                if ((object.ReferenceEquals(this.conductorField, value) != true)) {
                    this.conductorField = value;
                    this.RaisePropertyChanged("conductor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan hora {
            get {
                return this.horaField;
            }
            set {
                if ((this.horaField.Equals(value) != true)) {
                    this.horaField = value;
                    this.RaisePropertyChanged("hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Linea linea {
            get {
                return this.lineaField;
            }
            set {
                if ((object.ReferenceEquals(this.lineaField, value) != true)) {
                    this.lineaField = value;
                    this.RaisePropertyChanged("linea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Vehiculo vehiculo {
            get {
                return this.vehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.vehiculoField, value) != true)) {
                    this.vehiculoField = value;
                    this.RaisePropertyChanged("vehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Viaje[] viajes {
            get {
                return this.viajesField;
            }
            set {
                if ((object.ReferenceEquals(this.viajesField, value) != true)) {
                    this.viajesField = value;
                    this.RaisePropertyChanged("viajes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Conductor", Namespace="http://schemas.datacontract.org/2004/07/Share.Entities")]
    [System.SerializableAttribute()]
    public partial class Conductor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Horario[] horariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Persona personaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime vencimiento_libretaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Horario[] horarios {
            get {
                return this.horariosField;
            }
            set {
                if ((object.ReferenceEquals(this.horariosField, value) != true)) {
                    this.horariosField = value;
                    this.RaisePropertyChanged("horarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Persona persona {
            get {
                return this.personaField;
            }
            set {
                if ((object.ReferenceEquals(this.personaField, value) != true)) {
                    this.personaField = value;
                    this.RaisePropertyChanged("persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime vencimiento_libreta {
            get {
                return this.vencimiento_libretaField;
            }
            set {
                if ((this.vencimiento_libretaField.Equals(value) != true)) {
                    this.vencimiento_libretaField = value;
                    this.RaisePropertyChanged("vencimiento_libreta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vehiculo", Namespace="http://schemas.datacontract.org/2004/07/Share.Entities")]
    [System.SerializableAttribute()]
    public partial class Vehiculo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cant_asientosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Horario[] horarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> latitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> longitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string marcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string matriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modeloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cant_asientos {
            get {
                return this.cant_asientosField;
            }
            set {
                if ((this.cant_asientosField.Equals(value) != true)) {
                    this.cant_asientosField = value;
                    this.RaisePropertyChanged("cant_asientos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Horario[] horario {
            get {
                return this.horarioField;
            }
            set {
                if ((object.ReferenceEquals(this.horarioField, value) != true)) {
                    this.horarioField = value;
                    this.RaisePropertyChanged("horario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> latitud {
            get {
                return this.latitudField;
            }
            set {
                if ((this.latitudField.Equals(value) != true)) {
                    this.latitudField = value;
                    this.RaisePropertyChanged("latitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> longitud {
            get {
                return this.longitudField;
            }
            set {
                if ((this.longitudField.Equals(value) != true)) {
                    this.longitudField = value;
                    this.RaisePropertyChanged("longitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                if ((object.ReferenceEquals(this.marcaField, value) != true)) {
                    this.marcaField = value;
                    this.RaisePropertyChanged("marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string matricula {
            get {
                return this.matriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.matriculaField, value) != true)) {
                    this.matriculaField = value;
                    this.RaisePropertyChanged("matricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                if ((object.ReferenceEquals(this.modeloField, value) != true)) {
                    this.modeloField = value;
                    this.RaisePropertyChanged("modelo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://schemas.datacontract.org/2004/07/Share.Entities")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Admin adminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Conductor conductorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.SuperAdmin superadminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.TipoDocumento tipo_documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Usuario usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Admin admin {
            get {
                return this.adminField;
            }
            set {
                if ((object.ReferenceEquals(this.adminField, value) != true)) {
                    this.adminField = value;
                    this.RaisePropertyChanged("admin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoField, value) != true)) {
                    this.apellidoField = value;
                    this.RaisePropertyChanged("apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Conductor conductor {
            get {
                return this.conductorField;
            }
            set {
                if ((object.ReferenceEquals(this.conductorField, value) != true)) {
                    this.conductorField = value;
                    this.RaisePropertyChanged("conductor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasenia {
            get {
                return this.contraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.contraseniaField, value) != true)) {
                    this.contraseniaField = value;
                    this.RaisePropertyChanged("contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoField, value) != true)) {
                    this.correoField = value;
                    this.RaisePropertyChanged("correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string documento {
            get {
                return this.documentoField;
            }
            set {
                if ((object.ReferenceEquals(this.documentoField, value) != true)) {
                    this.documentoField = value;
                    this.RaisePropertyChanged("documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.SuperAdmin superadmin {
            get {
                return this.superadminField;
            }
            set {
                if ((object.ReferenceEquals(this.superadminField, value) != true)) {
                    this.superadminField = value;
                    this.RaisePropertyChanged("superadmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.TipoDocumento tipo_documento {
            get {
                return this.tipo_documentoField;
            }
            set {
                if ((this.tipo_documentoField.Equals(value) != true)) {
                    this.tipo_documentoField = value;
                    this.RaisePropertyChanged("tipo_documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Usuario usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Admin", Namespace="http://schemas.datacontract.org/2004/07/Share.Entities")]
    [System.SerializableAttribute()]
    public partial class Admin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Persona personaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Persona persona {
            get {
                return this.personaField;
            }
            set {
                if ((object.ReferenceEquals(this.personaField, value) != true)) {
                    this.personaField = value;
                    this.RaisePropertyChanged("persona");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SuperAdmin", Namespace="http://schemas.datacontract.org/2004/07/Share.Entities")]
    [System.SerializableAttribute()]
    public partial class SuperAdmin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalAutogestion.ServiceSOAP.Persona personaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalAutogestion.ServiceSOAP.Persona persona {
            get {
                return this.personaField;
            }
            set {
                if ((object.ReferenceEquals(this.personaField, value) != true)) {
                    this.personaField = value;
                    this.RaisePropertyChanged("persona");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSOAP.ISL_Soap")]
    public interface ISL_Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISL_Soap/EchoTest", ReplyAction="http://tempuri.org/ISL_Soap/EchoTestResponse")]
        string EchoTest(string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISL_Soap/EchoTest", ReplyAction="http://tempuri.org/ISL_Soap/EchoTestResponse")]
        System.Threading.Tasks.Task<string> EchoTestAsync(string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISL_Soap/ListarViajesDisponibles", ReplyAction="http://tempuri.org/ISL_Soap/ListarViajesDisponiblesResponse")]
        TerminalAutogestion.ServiceSOAP.ViajeDisponibleDTO[] ListarViajesDisponibles(System.DateTime fecha, int idParadaOrigen, int idParadaDestino);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISL_Soap/ListarViajesDisponibles", ReplyAction="http://tempuri.org/ISL_Soap/ListarViajesDisponiblesResponse")]
        System.Threading.Tasks.Task<TerminalAutogestion.ServiceSOAP.ViajeDisponibleDTO[]> ListarViajesDisponiblesAsync(System.DateTime fecha, int idParadaOrigen, int idParadaDestino);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISL_Soap/ReservarPasaje", ReplyAction="http://tempuri.org/ISL_Soap/ReservarPasajeResponse")]
        TerminalAutogestion.ServiceSOAP.Pasaje ReservarPasaje(int idViaje, int idParadaOrigen, int idParadaDestino, string documento, TerminalAutogestion.ServiceSOAP.TipoDocumento tipoDocumento, System.Nullable<int> asiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISL_Soap/ReservarPasaje", ReplyAction="http://tempuri.org/ISL_Soap/ReservarPasajeResponse")]
        System.Threading.Tasks.Task<TerminalAutogestion.ServiceSOAP.Pasaje> ReservarPasajeAsync(int idViaje, int idParadaOrigen, int idParadaDestino, string documento, TerminalAutogestion.ServiceSOAP.TipoDocumento tipoDocumento, System.Nullable<int> asiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISL_Soap/PrecioParaElegirAsiento", ReplyAction="http://tempuri.org/ISL_Soap/PrecioParaElegirAsientoResponse")]
        decimal PrecioParaElegirAsiento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISL_Soap/PrecioParaElegirAsiento", ReplyAction="http://tempuri.org/ISL_Soap/PrecioParaElegirAsientoResponse")]
        System.Threading.Tasks.Task<decimal> PrecioParaElegirAsientoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISL_SoapChannel : TerminalAutogestion.ServiceSOAP.ISL_Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SL_SoapClient : System.ServiceModel.ClientBase<TerminalAutogestion.ServiceSOAP.ISL_Soap>, TerminalAutogestion.ServiceSOAP.ISL_Soap {
        
        public SL_SoapClient() {
        }
        
        public SL_SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SL_SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SL_SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SL_SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string EchoTest(string mensaje) {
            return base.Channel.EchoTest(mensaje);
        }
        
        public System.Threading.Tasks.Task<string> EchoTestAsync(string mensaje) {
            return base.Channel.EchoTestAsync(mensaje);
        }
        
        public TerminalAutogestion.ServiceSOAP.ViajeDisponibleDTO[] ListarViajesDisponibles(System.DateTime fecha, int idParadaOrigen, int idParadaDestino) {
            return base.Channel.ListarViajesDisponibles(fecha, idParadaOrigen, idParadaDestino);
        }
        
        public System.Threading.Tasks.Task<TerminalAutogestion.ServiceSOAP.ViajeDisponibleDTO[]> ListarViajesDisponiblesAsync(System.DateTime fecha, int idParadaOrigen, int idParadaDestino) {
            return base.Channel.ListarViajesDisponiblesAsync(fecha, idParadaOrigen, idParadaDestino);
        }
        
        public TerminalAutogestion.ServiceSOAP.Pasaje ReservarPasaje(int idViaje, int idParadaOrigen, int idParadaDestino, string documento, TerminalAutogestion.ServiceSOAP.TipoDocumento tipoDocumento, System.Nullable<int> asiento) {
            return base.Channel.ReservarPasaje(idViaje, idParadaOrigen, idParadaDestino, documento, tipoDocumento, asiento);
        }
        
        public System.Threading.Tasks.Task<TerminalAutogestion.ServiceSOAP.Pasaje> ReservarPasajeAsync(int idViaje, int idParadaOrigen, int idParadaDestino, string documento, TerminalAutogestion.ServiceSOAP.TipoDocumento tipoDocumento, System.Nullable<int> asiento) {
            return base.Channel.ReservarPasajeAsync(idViaje, idParadaOrigen, idParadaDestino, documento, tipoDocumento, asiento);
        }
        
        public decimal PrecioParaElegirAsiento() {
            return base.Channel.PrecioParaElegirAsiento();
        }
        
        public System.Threading.Tasks.Task<decimal> PrecioParaElegirAsientoAsync() {
            return base.Channel.PrecioParaElegirAsientoAsync();
        }
    }
}
