//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalAutogestion.ServiceSOAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSOAP.ISL_Soap")]
    public interface ISL_Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISL_Soap/EchoTest", ReplyAction="http://tempuri.org/ISL_Soap/EchoTestResponse")]
        string EchoTest(string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISL_Soap/EchoTest", ReplyAction="http://tempuri.org/ISL_Soap/EchoTestResponse")]
        System.Threading.Tasks.Task<string> EchoTestAsync(string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISL_Soap/ListarViajesDisponibles", ReplyAction="http://tempuri.org/ISL_Soap/ListarViajesDisponiblesResponse")]
        Share.DTOs.ViajeDisponibleDTO[] ListarViajesDisponibles(System.DateTime fecha, int idParadaOrigen, int idParadaDestino);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISL_Soap/ListarViajesDisponibles", ReplyAction="http://tempuri.org/ISL_Soap/ListarViajesDisponiblesResponse")]
        System.Threading.Tasks.Task<Share.DTOs.ViajeDisponibleDTO[]> ListarViajesDisponiblesAsync(System.DateTime fecha, int idParadaOrigen, int idParadaDestino);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISL_Soap/ReservarPasaje", ReplyAction="http://tempuri.org/ISL_Soap/ReservarPasajeResponse")]
        Share.Entities.Pasaje ReservarPasaje(int idViaje, int idParadaOrigen, int idParadaDestino, string documento, Share.Enums.TipoDocumento tipoDocumento, System.Nullable<int> asiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISL_Soap/ReservarPasaje", ReplyAction="http://tempuri.org/ISL_Soap/ReservarPasajeResponse")]
        System.Threading.Tasks.Task<Share.Entities.Pasaje> ReservarPasajeAsync(int idViaje, int idParadaOrigen, int idParadaDestino, string documento, Share.Enums.TipoDocumento tipoDocumento, System.Nullable<int> asiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISL_Soap/PrecioParaElegirAsiento", ReplyAction="http://tempuri.org/ISL_Soap/PrecioParaElegirAsientoResponse")]
        decimal PrecioParaElegirAsiento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISL_Soap/PrecioParaElegirAsiento", ReplyAction="http://tempuri.org/ISL_Soap/PrecioParaElegirAsientoResponse")]
        System.Threading.Tasks.Task<decimal> PrecioParaElegirAsientoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISL_Soap/ListarParadas", ReplyAction="http://tempuri.org/ISL_Soap/ListarParadasResponse")]
        Share.Entities.Parada[] ListarParadas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISL_Soap/ListarParadas", ReplyAction="http://tempuri.org/ISL_Soap/ListarParadasResponse")]
        System.Threading.Tasks.Task<Share.Entities.Parada[]> ListarParadasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISL_SoapChannel : TerminalAutogestion.ServiceSOAP.ISL_Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SL_SoapClient : System.ServiceModel.ClientBase<TerminalAutogestion.ServiceSOAP.ISL_Soap>, TerminalAutogestion.ServiceSOAP.ISL_Soap {
        
        public SL_SoapClient() {
        }
        
        public SL_SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SL_SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SL_SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SL_SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string EchoTest(string mensaje) {
            return base.Channel.EchoTest(mensaje);
        }
        
        public System.Threading.Tasks.Task<string> EchoTestAsync(string mensaje) {
            return base.Channel.EchoTestAsync(mensaje);
        }
        
        public Share.DTOs.ViajeDisponibleDTO[] ListarViajesDisponibles(System.DateTime fecha, int idParadaOrigen, int idParadaDestino) {
            return base.Channel.ListarViajesDisponibles(fecha, idParadaOrigen, idParadaDestino);
        }
        
        public System.Threading.Tasks.Task<Share.DTOs.ViajeDisponibleDTO[]> ListarViajesDisponiblesAsync(System.DateTime fecha, int idParadaOrigen, int idParadaDestino) {
            return base.Channel.ListarViajesDisponiblesAsync(fecha, idParadaOrigen, idParadaDestino);
        }
        
        public Share.Entities.Pasaje ReservarPasaje(int idViaje, int idParadaOrigen, int idParadaDestino, string documento, Share.Enums.TipoDocumento tipoDocumento, System.Nullable<int> asiento) {
            return base.Channel.ReservarPasaje(idViaje, idParadaOrigen, idParadaDestino, documento, tipoDocumento, asiento);
        }
        
        public System.Threading.Tasks.Task<Share.Entities.Pasaje> ReservarPasajeAsync(int idViaje, int idParadaOrigen, int idParadaDestino, string documento, Share.Enums.TipoDocumento tipoDocumento, System.Nullable<int> asiento) {
            return base.Channel.ReservarPasajeAsync(idViaje, idParadaOrigen, idParadaDestino, documento, tipoDocumento, asiento);
        }
        
        public decimal PrecioParaElegirAsiento() {
            return base.Channel.PrecioParaElegirAsiento();
        }
        
        public System.Threading.Tasks.Task<decimal> PrecioParaElegirAsientoAsync() {
            return base.Channel.PrecioParaElegirAsientoAsync();
        }
        
        public Share.Entities.Parada[] ListarParadas() {
            return base.Channel.ListarParadas();
        }
        
        public System.Threading.Tasks.Task<Share.Entities.Parada[]> ListarParadasAsync() {
            return base.Channel.ListarParadasAsync();
        }
    }
}
