//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccesLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class uruguay_busEntities : DbContext
    {
        public uruguay_busEntities()
            : base("name=uruguay_busEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<conductor> conductor { get; set; }
        public virtual DbSet<horario> horario { get; set; }
        public virtual DbSet<linea> linea { get; set; }
        public virtual DbSet<parada> parada { get; set; }
        public virtual DbSet<parametro> parametro { get; set; }
        public virtual DbSet<pasaje> pasaje { get; set; }
        public virtual DbSet<persona> persona { get; set; }
        public virtual DbSet<precio> precio { get; set; }
        public virtual DbSet<superadmin> superadmin { get; set; }
        public virtual DbSet<tramo> tramo { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<vehiculo> vehiculo { get; set; }
        public virtual DbSet<viaje> viaje { get; set; }
    }
}
