//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class pasaje
    {
        public int id { get; set; }
        public Nullable<int> asiento { get; set; }
        public bool usado { get; set; }
        public Nullable<int> tipo_documento { get; set; }
        public string documento { get; set; }
        public Nullable<int> usuario_id { get; set; }
        public int viaje_id { get; set; }
        public int parada_id_origen { get; set; }
        public int parada_id_destino { get; set; }
    
        public virtual parada parada { get; set; }
        public virtual parada parada1 { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual viaje viaje { get; set; }
    }
}
