//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string correo { get; set; }
        public string contrasenia { get; set; }
        public string tipo_documento { get; set; }
        public string documento { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual conductor conductor { get; set; }
        public virtual superadmin superadmin { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
