//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class precio
    {
        public int id { get; set; }
        public decimal valor { get; set; }
        public System.DateTime fecha_validez { get; set; }
        public int parada_id { get; set; }
        public int linea_id { get; set; }
    
        public virtual tramo tramo { get; set; }
    }
}
